version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: pg-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  pg-network:

volumes:
  pg-data:
